### ISSUE TITLE
how can I compile example? 

### ISSUE THREAD

**Issue by adaptunit** [EduardSergeev/meta#1]
Try to see how it work.
I get error message... on R16B

readme.erl:none: undefined parse transform 'meta'

how can I compile "readme.erl" correctly?

please add  Makefile maybe it solve the problem

**Comment by EduardSergeev** [comment]
The error indicates that [parse_transform](http://www.erlang.org/doc/man/erl_id_trans.html) mechanism of Erlang compiler could not find `meta.beam` module. Just use `-pz` option of `erlc` to specify the path to the directory containing `memo.beam` (assuming that `meta` library has already been built using `rebar compile`):

```
 erlc readme.erl -pz ../ebin
```

Normally this dependency is taken care of by `rebar` when `meta` is specified as a dependency in `rebar.config`. In this case is it also preferable to use `-include_lib("meta/include/meta.hrl")` instead of `-include(..)`.

Anyway, I've added [Makefile](https://github.com/EduardSergeev/meta/blob/dev/example/Makefile) for convenience (in [dev](https://github.com/EduardSergeev/meta/tree/dev/example) branch).

**Comment by adaptunit** [comment]
oh ... many thanks for the tip - thanks to this I was able to run your examples! 
and now I cant play around... (I'm novice in erl)
many thanks again!
